SET APP=..\build-st_pattern-Desktop_Qt_5_5_1_MSVC2010_32bit-Release\release\st_pattern.exe

SET INTER_FILE_NAME=test

SET SEG_DATA="E:\Geolife Trajectories 1.3\Data\001"
SET SEG_SUFFIX=.plt
SET SEG_STEP=1.6
SET SEG_USE_SED=1
SET SEG_MIN_LEN=10

SET CLU_WEIGHT="0.001:0.001:0.001:0.001:0:0"
SET CLU_THRESH=0.0004
SET CLU_MEM_LIM=100

SET MINE_RADIUS=150.0
SET MINE_MIN_SUP=10
SET MINE_MIN_PAT_LEN=3


rem %APP% seg %SEG_DATA% %SEG_SUFFIX% %INTER_FILE_NAME% %SEG_STEP% %SEG_USE_SED% %SEG_MIN_LEN%

rem %APP% cluster %INTER_FILE_NAME% %CLU_WEIGHT% %INTER_FILE_NAME% %CLU_THRESH% %CLU_MEM_LIM%

%APP% mine %INTER_FILE_NAME% %INTER_FILE_NAME% %INTER_FILE_NAME% %MINE_RADIUS% %MINE_MIN_SUP% %MINE_MIN_PAT_LEN%

del *.cluster
del *.s2c
del *.seg
del *.stp
del *.tinc
del *.tins